<#
.SYNOPSIS
  Writes the lazy.nvim plugin spec for the token-monitor status segment.

.DESCRIPTION
  Writes a `dir=` plugin spec into ~/AppData/Local/nvim/lua/plugins/ pointing
  at this package -- a local plugin, not a git remote. Idempotent; re-run it
  after moving the suite. Skips, rather than fails, with no Neovim config dir.

.PARAMETER SuiteRoot
  Override the auto-detected suite root (defaults to two levels up).
#>
param(
    [string]$SuiteRoot
)

$ErrorActionPreference = "Stop"

$scriptRoot = $PSScriptRoot
if (-not $SuiteRoot) { $SuiteRoot = Split-Path (Split-Path $scriptRoot -Parent) -Parent }
$SuiteRoot = (Resolve-Path $SuiteRoot).Path.TrimEnd('\', '/')
$fwd = $SuiteRoot -replace '\\', '/'

$nvimPluginDir = "$env:LOCALAPPDATA\nvim\lua\plugins"
$nvimRoot      = Split-Path $nvimPluginDir -Parent

if (-not (Test-Path $nvimRoot)) {
    Write-Host "  [skip] no Neovim config dir at $nvimRoot"
    return
}

if (-not (Test-Path $nvimPluginDir)) { New-Item -ItemType Directory -Path $nvimPluginDir -Force | Out-Null }

$spec = @"
return {
  -- Generated by claude-token-monitor's install.ps1 -- edits here are lost.
  -- Re-run it if the suite moves.
  dir = "$fwd/packages/token-monitor.nvim",
  name = "claude-token-monitor",
  lazy = false,
  opts = {
    -- "statusline" (bottom, default) or "winbar" (top, per-window).
    -- position = "statusline",
  },
}
"@

# No-BOM UTF-8 -- see the suite CLAUDE.md "PowerShell 5.1 encoding"
[System.IO.File]::WriteAllText("$nvimPluginDir\claude-token-monitor.lua", $spec, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  [ok]   $nvimPluginDir\claude-token-monitor.lua"
