<#
.SYNOPSIS
  Writes the lazy.nvim plugin spec for the token-monitor status segment.

.DESCRIPTION
  Drops a `dir=` plugin spec into ~/AppData/Local/nvim/lua/plugins/ pointing
  at this package. Local plugin, not a git remote -- lazy.nvim loads it from
  the suite in place.

  Skipped (not failed) when there is no Neovim config directory: this is an
  optional integration and a machine without nvim is not a broken install.

  Idempotent. Re-run it after moving the suite.

.PARAMETER SuiteRoot
  Override the auto-detected suite root (defaults to two levels up).
#>
param(
    [string]$SuiteRoot
)

$ErrorActionPreference = "Stop"

$scriptRoot = $PSScriptRoot   # .../packages/token-monitor.nvim
if (-not $SuiteRoot) { $SuiteRoot = Split-Path (Split-Path $scriptRoot -Parent) -Parent }
$SuiteRoot = (Resolve-Path $SuiteRoot).Path.TrimEnd('\', '/')
$fwd = $SuiteRoot -replace '\\', '/'

$nvimPluginDir = "$env:LOCALAPPDATA\nvim\lua\plugins"
$nvimRoot      = Split-Path $nvimPluginDir -Parent

if (-not (Test-Path $nvimRoot)) {
    Write-Host "  [skip] no Neovim config dir at $nvimRoot"
    return
}

if (-not (Test-Path $nvimPluginDir)) { New-Item -ItemType Directory -Path $nvimPluginDir -Force | Out-Null }

# The plugin resolves its own status.json location relative to its own file
# path (see lua/claude-token-monitor/config.lua), so the only thing that needs
# writing here is where the plugin itself is.
$spec = @"
return {
  -- Generated by claude-token-monitor's install.ps1 -- re-run it if the
  -- suite moves. Local ``dir=`` plugin, not a git remote. The watcher daemon
  -- and llama.cpp server are separate packages in the same suite, not
  -- managed by lazy.nvim; this plugin only reads the status.json they write.
  dir = "$fwd/packages/token-monitor.nvim",
  name = "claude-token-monitor",
  lazy = false,
  opts = {
    -- "statusline" (bottom, default) or "winbar" (top, per-window).
    -- position = "statusline",
  },
}
"@

# No-BOM UTF-8: Neovim reads this file as Lua source, and a BOM shows up as a
# stray character before `return`.
[System.IO.File]::WriteAllText("$nvimPluginDir\claude-token-monitor.lua", $spec, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  [ok]   $nvimPluginDir\claude-token-monitor.lua"
